all : libs progs

DEPS=
DRIVER_DEPS=centaur

MY_FLAGS=-I../../libs/hokuyo/include/cpp -I../../libs/libjson -DNDEBUG
MY_LIBS=../../libs/libjson/libjson.a ../../libs/hokuyo/src/liburg_cpp.a ../../libs/hokuyo/src/liburg_c.a 

include ../rules.mk
