all : libs progs

DEPS=
DRIVER_DEPS=centaur

MY_FLAGS=-DNDEBUG
MY_LIBS=-lglut -lGLU -lGL -lXmu -lX11

include ../rules.mk

#run : bin/pubKinect bin/subKinect
#	gnome-terminal -x /bin/bash -c ./bin/pubKinect &
#	bin/subKinect &
