g++ -o main_GlovePublisher src/main_GlovePublisher.cpp  -I../../libs/zmq/include -Iinclude -L../../libs/zmq/lib -lzmq -lrt


g++ -o main_GloveRequester src/main_GloveRequester.cpp  -I../../libs/zmq/include -Iinclude -L../../libs/zmq/lib -lzmq -lrt
