#include "fk_leftarm.h"
#include "fk_rightarm.h"

int main(int argc, char *argv[])
{
  float LEFTARM_FOREARM_ROTATE;
  float LEFTARM_ELBOW;
  float LEFTARM_BICEP_ROTATE;
  float LEFTARM_SHOULDER_UD;
  float LEFTARM_SHOULDER_IO;
  float leftpose[4][4];

  float RIGHTARM_FOREARM_ROTATE;
  float RIGHTARM_ELBOW;
  float RIGHTARM_BICEP_ROTATE;
  float RIGHTARM_SHOULDER_UD;
  float RIGHTARM_SHOULDER_IO;
  float rightpose[4][4];

  fk_leftarm(LEFTARM_SHOULDER_IO,LEFTARM_SHOULDER_UD,LEFTARM_BICEP_ROTATE,LEFTARM_ELBOW,LEFTARM_FOREARM_ROTATE,leftpose);

  fk_rightarm(RIGHTARM_SHOULDER_IO,RIGHTARM_SHOULDER_UD,RIGHTARM_BICEP_ROTATE,RIGHTARM_ELBOW,RIGHTARM_FOREARM_ROTATE,rightpose);

}
