% :
	$(MAKE) -C servos $@
	$(MAKE) -C proxyservos $@
	$(MAKE) -C body $@
	$(MAKE) -C webcamPublisher $@
	$(MAKE) -C LidarProvider $@
	$(MAKE) -C sensors $@
	$(MAKE) -C proxysensors $@
	$(MAKE) -C safetyProvider $@


