#!/bin/sh
HERE=`dirname $0`
HERE=`realpath "$HERE"`
# add this binary's directory to path
PATH="$HERE/bin:$PATH"

# add required dynamic libraries
export LD_LIBRARY_PATH="$HERE/../../libs/lib:$LD_LIBRARY_PATH"

# run 
bin/TestZMQServoController "$*"
