all :
	$(MAKE) -C libnow all
	$(MAKE) -C libzmqpp all
	$(MAKE) -C libservos all
	$(MAKE) -C servos all
	$(MAKE) -C testservo all
	$(MAKE) -C walker all
	$(MAKE) -C body all
	$(MAKE) -C commander all

clean :
	$(MAKE) -C libnow clean
	$(MAKE) -C libzmqpp clean
	$(MAKE) -C libservos clean
	$(MAKE) -C servos clean
	$(MAKE) -C testservos clean
	$(MAKE) -C walker clean
	$(MAKE) -C body all
	$(MAKE) -C commander all

