#!/bin/bash

export MOJAVATON_DIR=$(realpath $(dirname $0)/..)

# add bin folders to PATH
for bin in $MOJAVATON_DIR/drivers/*/bin
do
    PATH="$bin:$PATH"
done

# add 3rd party and project library paths
for lib in $MOJAVATON_DIR/libs/lib $MOJAVATON_DIR/drivers/*/lib
do
    export LD_LIBRARY_PATH="$lib:$LD_LIBRARY_PATH"
done


"$@"
