#!/bin/bash

# add bin folders to PATH
for bin in $(realpath $(dirname $0))/*/bin
do
  PATH="$(realpath $bin):$PATH"
done

# add 3rd party and project library paths
for lib in ../libs/lib $(realpath $(dirname $0))/*/lib
do
  export LD_LIBRARY_PATH="$(realpath $lib):$LD_LIBRARY_PATH"
done

"$@"
