# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.4
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.



from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_body', [dirname(__file__)])
        except ImportError:
            import _body
            return _body
        if fp is not None:
            try:
                _mod = imp.load_module('_body', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _body = swig_import_helper()
    del swig_import_helper
else:
    import _body
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


class Body(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Body, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Body, name)
    __repr__ = _swig_repr
    __swig_setmethods__["legs"] = _body.Body_legs_set
    __swig_getmethods__["legs"] = _body.Body_legs_get
    if _newclass:legs = _swig_property(_body.Body_legs_get, _body.Body_legs_set)
    __swig_setmethods__["waist"] = _body.Body_waist_set
    __swig_getmethods__["waist"] = _body.Body_waist_get
    if _newclass:waist = _swig_property(_body.Body_waist_get, _body.Body_waist_set)
    __swig_setmethods__["neck"] = _body.Body_neck_set
    __swig_getmethods__["neck"] = _body.Body_neck_get
    if _newclass:neck = _swig_property(_body.Body_neck_get, _body.Body_neck_set)
    __swig_setmethods__["left"] = _body.Body_left_set
    __swig_getmethods__["left"] = _body.Body_left_get
    if _newclass:left = _swig_property(_body.Body_left_get, _body.Body_left_set)
    __swig_setmethods__["right"] = _body.Body_right_set
    __swig_getmethods__["right"] = _body.Body_right_get
    if _newclass:right = _swig_property(_body.Body_right_get, _body.Body_right_set)
    def init(self): return _body.Body_init(self)
    def report(self, *args): return _body.Body_report(self, *args)
    def __init__(self): 
        this = _body.new_Body()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _body.delete_Body
    __del__ = lambda self : None;
Body_swigregister = _body.Body_swigregister
Body_swigregister(Body)

MOVE_RATE = _body.MOVE_RATE
ANGLE360 = _body.ANGLE360
ANGLE180 = _body.ANGLE180
ANGLE90 = _body.ANGLE90
ANGLE45 = _body.ANGLE45
HIPAXISX = _body.HIPAXISX
HIPAXISY = _body.HIPAXISY
LEG1 = _body.LEG1
LEG2 = _body.LEG2
LEG3 = _body.LEG3
LEG4 = _body.LEG4

def servo(*args):
  return _body.servo(*args)
servo = _body.servo
# This file is compatible with both classic and new-style classes.

cvar = _body.cvar

