#!/bin/bash

# find mojavaton base directory
if [ -z "$MOJAVATON_DIR" -o ! -d $MOJAVATON_DIR/drivers ]
then
  for ups in . .. ../.. ../../.. ../../../..
  do
    if [ -d $(dirname $0)/$ups/drivers ]
    then
      export MOJAVATON_DIR=$(realpath $(dirname $0)/$ups)
      break
    fi
  done
fi

if [ -z "$MOJAVATON_DIR" -o ! -d $MOJAVATON_DIR/drivers ]
then
  echo "could not determine base mojavaton directory"
  exit 1
fi

setup()
{
  # add bin folders to PATH
  for bin in $MOJAVATON_DIR/drivers/*/bin $MOJAVATON_DIR/control/*/bin
  do
    PATH="$bin:$PATH"
  done

  # add 3rd party and project library paths
  for lib in $MOJAVATON_DIR/libs/lib $MOJAVATON_DIR/drivers/*/lib $MOJAVATON_DIR/control/*/lib
  do
    export LD_LIBRARY_PATH="$lib:$LD_LIBRARY_PATH"
  done
}

update()
{
  for dir in setup libs drivers centaur control
  do
      svn update $MOJAVATON_DIR/$dir
  done
}

build()
{
  for dir in libs drivers
  do
      make -C $MOJAVATON_DIR/$dir "$@"
  done
}

commit()
{
  for dir in setup libs drivers centaur control
  do
      svn commit -m "$@ - in $dir" $MOJAVATON_DIR/$dir
  done
}

commander()
{
    cd $MOJAVATON_DIR/control/commander
    bin/commander
}

setup

"$@"
