% :
	$(MAKE) -C commander $@
	$(MAKE) -C glovePublisher $@
	$(MAKE) -C webcamRequester $@
	$(MAKE) -C gui $@
	$(MAKE) -C joystickProvider $@ 
	$(MAKE) -C leapPublisher $@
	$(MAKE) -C heartBeatRequester $@
	$(MAKE) -C guicmdr $@


