#!/bin/bash

# add this scripts folder's bin directory to path
PATH="$(realpath $(dirname $0))/bin:$PATH"

# add 3rd party and project library paths
for lib in ../../libs/lib ../lib*/lib
do
  export LD_LIBRARY_PATH="$(realpath $lib):$LD_LIBRARY_PATH"
done

"$@"
