all : libs progs

DRIVER_DEPS=centaur utilities
MY_FLAGS=-I../../libs/hokuyo/include/cpp -I../../libs/libjson -I../../libs/libjson/_internal/Source -I../../libs/libjson/_internal/Source/JSONDefs
MY_LIBS=-L../../libs/hokuyo/src -lurg_cpp -lurg_c

include ../rules.mk
